OPTIONS (SKIP=1)
LOAD DATA
APPEND INTO TABLE OPERADOR
(
idOperador INTEGER EXTERNAL TERMINATED BY ",",
nombre CHAR TERMINATED BY ",",
direccion CHAR TERMINATED BY ",",
telefono INTEGER EXTERNAL TERMINATED BY ",",
tipoDeOperador CHAR TERMINATED BY ","
)