SELECT OPERADOR.IDOPERADOR, OPERADOR.NOMBRE, SUM (OFERTA.VALOR) AS INGRESOS
FROM 
    OPERADOR INNER JOIN (RESERVA INNER JOIN OFERTA ON RESERVA.IDOFERTA = 
    OFERTA.IDOFERTA) ON OPERADOR.IDOPERADOR = OFERTA.IDOPERADOR

WHERE EXTRACT(YEAR FROM RESERVA.FECHARESERVA) = EXTRACT(YEAR FROM CURRENT_TIMESTAMP)
AND RESERVA.ESTADORESERVA='finalizado' 
GROUP BY OPERADOR.NOMBRE, OPERADOR.IDOPERADOR;