SELECT OPERADOR.IDOPERADOR, OPERADOR.NOMBRE, SUM(OFERTA.VALOR) AS INGRESOS 
FROM  (OPERADOR INNER JOIN (RESERVA INNER JOIN OFERTA ON RESERVA.IDOFERTA = OFERTA.IDOFERTA) ON OPERADOR.IDOPERADOR = OFERTA.IDOPERADOR)
WHERE RESERVA.ESTADORESERVA='finalizado'
Group by OPERADOR.IDOPERADOR, OPERADOR.NOMBRE;