SELECT TOP_POPULA, IDOFERTA, TIPODEOFERTA, DISPONIBLE, VALOR, FECHA_INICIO, FECHA_FINAL
FROM(

    SELECT OFERTA.IDOFERTA AS IDOFERTA, OFERTA.TIPODEOFERTA AS TIPODEOFERTA, OFERTA.CANTIDADDISPONIBLE AS DISPONIBLE,
    OFERTA.VALOR AS VALOR,OFERTA.FECHAINICIO AS FECHA_INICIO,OFERTA.FECHAFINAL AS FECHA_FINAL,
    
    COUNT(OFERTA.IDOFERTA) AS RESERVAS ,ROW_NUMBER() OVER (ORDER BY  COUNT (OFERTA.IDOFERTA) DESC)AS TOP_POPULA
    
    FROM OFERTA INNER JOIN RESERVA ON RESERVA.IDOFERTA = OFERTA.IDOFERTA AND OFERTA.ESTADOOFERTA='habilitado'
    GROUP BY OFERTA.IDOFERTA, OFERTA.TIPODEOFERTA, OFERTA.CANTIDADDISPONIBLE, OFERTA.VALOR, OFERTA.FECHAINICIO,OFERTA.FECHAFINAL
    ORDER BY OFERTA.IDOFERTA)

WHERE TOP_POPULA<20
ORDER BY TOP_POPULA;