SELECT OFERTA.IDOFERTA, OFERTA.FECHAINICIO, OFERTA.FECHAFINAL, COUNT(*) 
FROM ISIS2304A721810.OFERTA INNER JOIN ISIS2304A721810.SERVICIO ON SERVICIO.IDOFERTA = OFERTA.IDOFERTA 
WHERE OFERTA.FECHAINICIO >= TO_DATE('12-04-2018', 'DD-MM-YYYY') AND OFERTA.FECHAFINAL<= TO_DATE('20-07-2018', 'DD-MM-YYYY') 
      AND OFERTA.CANTIDADDISPONIBLE>0 AND OFERTA.ESTADOOFERTA='habilitado' 	AND SERVICIO.NOMBRESERVICIO= 'agua' OR  SERVICIO.NOMBRESERVICIO= 'internet'
GROUP BY OFERTA.IDOFERTA, OFERTA.FECHAINICIO, OFERTA.FECHAFINAL HAVING COUNT(*) = 2;