SELECT * 
FROM(
SELECT OFERTA.IDOFERTA, OFERTA.FECHAINICIO, OFERTA.FECHAFINAL, SERVICIO.NOMBRESERVICIO AS SERVICIOS
FROM OFERTA INNER JOIN SERVICIO ON SERVICIO.IDOFERTA = OFERTA.IDOFERTA
WHERE OFERTA.FECHAINICIO>='01/08/18' AND OFERTA.FECHAFINAL<='30/12/18' 
)