SELECT PERSONAHABILITADA.NOMBRE, OFERTA.TIPODEOFERTA AS CARACTERISTICA, OFERTA.DURACION AS DIAS_CONTRATADOS, OFERTA.VALOR AS VALOR_DIA
FROM ((PERSONAHABILITADA INNER JOIN RESERVA ON RESERVA.IDPERSONAHABILITADA = PERSONAHABILITADA.IDPERSONAHABILITADA)
INNER JOIN OFERTA ON RESERVA.IDOFERTA = OFERTA.IDOFERTA)
WHERE RESERVA.ESTADORESERVA='finalizado' AND PERSONAHABILITADA.NOMBRE LIKE 'German Enrique%';